In [2]:
import pandas as pd
import numpy as np

In [4]:
# Datafeeder starting parameters (right now it'll be hardcoded, and later, it will be fetched from a datafeeder_config variable)
data_inputs = {'1min':{'columns':['open', 'high', 'low', 'close', 'volume,' 'SMA15', 'SMA30'], 'lookback':100}, '1d':{'columns':['open', 'high', 'low', 'close', 'volume,' 'SMA15', 'SMA30'], 'lookback':100}}
tickers = ['AAPL', 'MSFT', 'NVDA']

datafeeder_config = {'data_inputs':data_inputs, 'tickers':tickers}

In [6]:
# Create date ranges
date_range_1min = pd.date_range(start='2023-01-01', periods=100, freq='min')
date_range_1d = pd.date_range(start='2023-01-01', periods=100, freq='D')

# Generate random prices and other data
np.random.seed(0)

def generate_data(date_range, granularity):
    data = []
    for date in date_range:
        for ticker in tickers:
            open_price = np.random.uniform(100, 200)
            high_price = open_price + np.random.uniform(0, 10)
            low_price = open_price - np.random.uniform(0, 10)
            close_price = np.random.uniform(low_price, high_price)
            volume = np.random.randint(1000, 10000)
            sma15 = np.random.uniform(100, 200)
            sma30 = np.random.uniform(100, 200)
            data.append([granularity, date, ticker, open_price, high_price, low_price, close_price, volume, sma15, sma30])
    return data

data_1min = generate_data(date_range_1min, '1min')
data_1d = generate_data(date_range_1d, '1d')

# Create DataFrames
columns = ['Granularity', 'Datetime', 'Ticker', 'Open', 'High', 'Low', 'Close', 'Volume', 'SMA15', 'SMA30']
df_1min = pd.DataFrame(data_1min, columns=columns)
df_1d = pd.DataFrame(data_1d, columns=columns)

# Concatenate DataFrames
df = pd.concat([df_1min, df_1d])

# Set multi-index
df.set_index(['Granularity', 'Datetime', 'Ticker'], inplace=True)

# Pivot the DataFrame to have tickers as columns
df = df.unstack(level='Ticker')

In [88]:
# # Filter for '1min' granularity and 'AAPL' ticker
df.loc['1min'].xs('AAPL', axis=1, level='Ticker').index()

TypeError: 'DatetimeIndex' object is not callable

In [82]:
# Get the 'Close' prices for '1min' granularity and 'AAPL' ticker
df.loc['1min'].xs('AAPL', axis=1, level='Ticker')['Close']

                           Open                                High  \
Ticker                     AAPL        MSFT        NVDA        AAPL
Datetime
2023-01-01 00:00:00  154.881350  189.177300  107.103606  162.033244
2023-01-01 00:01:00  147.360805  194.466892  132.414101  155.369912
2023-01-01 00:02:00  190.234858  160.783067  199.529957  191.227662
2023-01-01 00:03:00  165.632959  167.365963  103.918779  167.014788
2023-01-01 00:04:00  106.414750  108.311249  158.651293  113.339471
...                         ...         ...         ...         ...
2023-01-01 01:35:00  115.148601  112.961905  121.151798  116.769331
2023-01-01 01:36:00  137.558856  106.290696  181.151847  141.149921
2023-01-01 01:37:00  184.267801  103.921054  198.114177  185.904532
2023-01-01 01:38:00  126.798868  164.364401  139.618456  127.417760
2023-01-01 01:39:00  162.911562  193.345589  196.828552  165.244272

                                                    Low              \
Ticker                     MSFT        NVDA        AAPL        MSFT
Datetime
2023-01-01 00:00:00  198.813928  107.974899  148.853717  185.342885
2023-01-01 00:01:00  199.685375  133.910849  142.156030  190.320272
2023-01-01 00:02:00  164.033539  205.348460  180.536768  160.398813
2023-01-01 00:03:00  177.085413  106.746849  163.667135  158.584028
2023-01-01 00:04:00  111.088435  158.852369  100.748735  108.217682
...                         ...         ...         ...         ...
2023-01-01 01:35:00  113.009779  129.461280  105.513901  107.424244
2023-01-01 01:36:00  115.834705  185.912687  131.392672  104.801110
2023-01-01 01:37:00  104.173372  199.621328  181.665276  101.205551
2023-01-01 01:38:00  168.583223  145.637893  118.585833  159.593407
2023-01-01 01:39:00  195.874128  200.358648  157.752828  185.767348

                                      Close  ...             Volume        \
Ticker                     NVDA        AAPL  ...        NVDA   AAPL  MSFT
Datetime                                     ...
2023-01-01 00:00:00  106.901422  156.035019  ...  107.795220   8891  3222
2023-01-01 00:01:00  130.190887  151.126664  ...  131.628611   9615  2207
2023-01-01 00:02:00  195.386271  187.519419  ...  200.115297   9622  8108
2023-01-01 00:03:00  102.716814  164.901499  ...  103.910269   8365  5464
2023-01-01 00:04:00  150.361893  104.090184  ...  150.401760   6531  6302
...                         ...         ...  ...         ...    ...   ...
2023-01-01 01:35:00  120.459950  108.946404  ...  128.261429   5970  7555
2023-01-01 01:36:00  175.920287  140.178198  ...  178.423589   6351  6708
2023-01-01 01:37:00  196.491659  183.238961  ...  196.850572   3042  6245
2023-01-01 01:38:00  138.984766  121.939020  ...  141.711600   8452  9371
2023-01-01 01:39:00  195.233586  159.550982  ...  196.214075   6247  9423

                                SMA15                               SMA30  \
Ticker               NVDA        AAPL        MSFT        NVDA        AAPL
Datetime
2023-01-01 00:00:00  3046  164.589411  156.804456  114.035078  143.758721
2023-01-01 00:01:00  2641  163.992102  121.655035  144.994999  114.335329
2023-01-01 00:02:00  8098  135.815217  165.279032  115.896958  175.068614
2023-01-01 00:03:00  7521  101.357164  160.484552  131.798318  162.284610
2023-01-01 00:04:00  9829  191.672295  128.940609  156.961841  192.115761
...                   ...         ...         ...         ...         ...
2023-01-01 01:35:00  8557  107.561067  110.218421  173.193028  146.080304
2023-01-01 01:36:00  7508  117.871711  164.386404  105.856741  183.817550
2023-01-01 01:37:00  7115  126.810926  119.217325  185.273616  113.159685
2023-01-01 01:38:00  2026  166.681695  153.699889  122.538292  158.903112
2023-01-01 01:39:00  6999  197.477442  113.620326  166.797707  104.928526


Ticker                     MSFT        NVDA
Datetime
2023-01-01 00:00:00  192.559664  187.008726
2023-01-01 00:01:00  113.521817  161.306346
2023-01-01 00:02:00  163.505887  111.037514
2023-01-01 00:03:00  173.926358  141.426299
2023-01-01 00:04:00  118.319136  170.373728
...                         ...         ...
2023-01-01 01:35:00  182.697445  134.222633
2023-01-01 01:36:00  150.177313  121.993997
2023-01-01 01:37:00  176.133028  135.020195
2023-01-01 01:38:00  197.885698  179.359704
2023-01-01 01:39:00  146.794710  184.083024

[100 rows x 21 columns]